#!/bin/bash

# Function to display information about a subdomain
audit_subdomain() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short $sub.$domain)

        if [ -z "$result" ]; then
            echo "The subdomain $sub does not exist."
        else
            record_type=$(dig +short $sub.$domain | awk 'NR==1{print $4}')
            destination=$(dig +short $sub.$domain)

            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Call the audit_subdomain function with provided arguments
audit_subdomain "$1" "$2"

