#!/bin/bash
sudo apt-get update
sudo apt-get install haproxy

sudo apt-get install certbot

sudo certbot certonly --standalone -d www.yourdomain.com

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.yourdomain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80 check

sudo service haproxy restart

curl -sI https://www.yourdomain.com
curl https://www.yourdomain.com

